/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import FileSystem.Comandos;
import FileSystem.Sistema;
import java.io.File;
import java.io.FileWriter;
import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

public class MainPanel extends javax.swing.JPanel {

    private Scanner scan;
    private Sistema sistema;
    
    /**
     * Creates new form MainPanel
     */
    public MainPanel(Sistema sistema) {
        initComponents();
        
        this.sistema = sistema;
        
        try {
            scan = new Scanner(new File("historial.txt"));
            
            while (scan.hasNextLine()) {
                String[] comando = scan.nextLine().split("_");

                switch(comando[0]){
                case "GOCHILD":
                    consola.append(Comandos.ingresarDirectorio(this, sistema, comando[1]) + "\n");
                    break;
                case "GOPARENT":
                    consola.append(Comandos.regresarPadre(this, sistema) + "\n");
                    break;
                case "CREATEFILE":
                    consola.append(Comandos.crearArchivo(this, sistema, comando) + "\n");
                    break;
                case "CREATEDIR":
                    consola.append(Comandos.crearDirectorio(this, sistema, comando[1]) + "\n");
                    break;
                case "DELETEFILE":
                    consola.append(Comandos.borrarArchivo(this, sistema, comando[1]) + "\n");
                    break;
                case "DELETEDIR":
                    consola.append(Comandos.borrarDirectorio(this, sistema, comando[1]) + "\n");
                    break;
                }
            
            }
            
            consola.setText("");
                
            scan.close();
            
        } catch (Exception e) {
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        boton_salir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        consola = new javax.swing.JTextArea();
        text_cmd = new javax.swing.JTextField();
        boton_ejecutar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel2.setText("File System Manager");

        boton_salir.setText("Salir");
        boton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_salirActionPerformed(evt);
            }
        });

        consola.setEditable(false);
        consola.setColumns(20);
        consola.setRows(5);
        jScrollPane2.setViewportView(consola);

        boton_ejecutar.setText("Ejecutar comando");
        boton_ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_ejecutarActionPerformed(evt);
            }
        });

        jLabel1.setText("Consola");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(text_cmd))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel2)
                        .addGap(0, 125, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boton_salir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(boton_ejecutar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_cmd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(boton_ejecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void boton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_boton_salirActionPerformed

    private void boton_ejecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_ejecutarActionPerformed
        
        consola.append("------------------------------------------------------------\n");
        
        String[] comando = text_cmd.getText().split("_");
        
        try {
            FileWriter write_historial = new FileWriter("historial.txt", true);
            
            switch(comando[0]){
           
            case "SHOWDIR":
                consola.append(Comandos.directorioActual(this, sistema) + "\n");
                break;
            case "GOCHILD":
                consola.append(Comandos.ingresarDirectorio(this, sistema, comando[1]) + "\n");
                write_historial.append(text_cmd.getText() + "\n");
                break;
            case "GOPARENT":
                consola.append(Comandos.regresarPadre(this, sistema) + "\n");
                write_historial.append(text_cmd.getText() + "\n");
                break;
            case "CREATEFILE":
                consola.append(Comandos.crearArchivo(this, sistema, comando) + "\n");
                write_historial.append(text_cmd.getText() + "\n");
                break;
            case "CREATEDIR":
                consola.append(Comandos.crearDirectorio(this, sistema, comando[1]) + "\n");
                write_historial.append(text_cmd.getText() + "\n");
                break;
            case "DELETEFILE":
                consola.append(Comandos.borrarArchivo(this, sistema, comando[1]) + "\n");
                write_historial.append(text_cmd.getText() + "\n");
                break;
            case "DELETEDIR":
                consola.append(Comandos.borrarDirectorio(this, sistema, comando[1]) + "\n");
                write_historial.append(text_cmd.getText() + "\n");
                break;
            case "SHOWFILE":
                consola.append(Comandos.verArchivo(this, sistema, comando[1]) + "\n");
                break;
            case "LISTCONT":
                consola.append(Comandos.listarContenido(this, sistema) + "\n");
                break;
            case "SHOWSTORAGE":
                consola.append(Comandos.verEspacioDisponible(sistema) + "\n");
                break;
            case "FORMAT":
                int option = JOptionPane.showConfirmDialog(this, "ESTA SEGURO DE CONTINUAR?");
                if (option == 0) {
                    Comandos.format(this, sistema);
                } else {
                    consola.append("OPERACION ABORTADA\n");
                }
                break;
            case "STAT":
                consola.append(Comandos.estadisticas(this, sistema) + "\n");
                break;
            case "CLEAR":
                consola.setText("");
                break;
            case "":
                break;
            default:
                consola.append("CODIGO NO VALIDO, REVISAR SINTAXIS\n");
                break;
            
            }
            
            write_historial.close();
                
        } catch (Exception e) {
            e.printStackTrace();
            consola.append("CODIGO NO VALIDO, REVISAR SINTAXIS\n");
            
        }
        
    }//GEN-LAST:event_boton_ejecutarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_ejecutar;
    private javax.swing.JButton boton_salir;
    private javax.swing.JTextArea consola;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField text_cmd;
    // End of variables declaration//GEN-END:variables

}
